# Generated by Django 2.2.7 on 2020-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cCompanyName', models.CharField(max_length=100)),
                ('cVacantPost', models.CharField(max_length=100)),
                ('cVacancyNumber', models.IntegerField(max_length=100)),
                ('cEmail', models.EmailField(max_length=100)),
                ('cMobile', models.IntegerField(max_length=10)),
                ('cLocation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
    ]
